import Layout from "'@/layout/Layout'";
import './globals.scss';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'GYM',
  description: 'Generated by create next app',
  icons: [
    { rel: 'icon', url: 'icon/favicon.ico' },
    { rel: 'apple-touch-icon', url: 'icon/apple-touch.ico' },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <Layout>{children}</Layout>
    </html>
  );
}
