import { integral } from "'@/assets/styles/fonts'";
import "./globals.css";

export const metadata = {
  title: "GYM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"flex justify-center m-auto bg-black text-white"}>
        {children}
      </body>
    </html>
  );
}
