"use client";

import Layout from "'@/layout/Layout'";
import { ThemeProvider } from "@emotion/react";
import "./globals.scss";
import { theme } from "'@/assets/styles/theme'";

export const metadata = {
  title: "GYM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>
      <Layout>{children}</Layout>
    </ThemeProvider>
  );
}
